/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 10/07/2021 19:59:09
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_SYSCLKFreq_VALUE                     4000000
#define MX_HCLKFreq_Value                       4000000
#define MX_FCLKCortexFreq_Value                 4000000
#define MX_CortexFreq_Value                     4000000
#define MX_AHBFreq_Value                        4000000
#define MX_APB1Freq_Value                       4000000
#define MX_APB2Freq_Value                       4000000
#define MX_APB1TimFreq_Value                    4000000
#define MX_APB2TimFreq_Value                    4000000
#define MX_PWRFreq_Value                        4000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        32000000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    4000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ADCx_IN6_Pin                         PA1
#define MX_ADCx_IN6_GPIOx                       GPIOA
#define MX_ADCx_IN6_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADCx_IN6_GPIO_Pin                    GPIO_PIN_1
#define MX_ADCx_IN6_GPIO_Mode                   GPIO_MODE_ANALOG_ADC_CONTROL

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB6 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_GPIO_FM6                    __NULL
#define MX_I2C1_SCL_Pin                         PB6
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_6
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB9 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PB9
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_9
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD
#define MX_I2C1_SDA_GPIO_FM9                    __NULL

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 (JTMS-SWDIO) */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13_JTMS_SWDIO

/* Pin PA14 (JTCK-SWCLK) */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14_JTCK_SWCLK

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA12 */
#define MX_PA12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PA12_Pin                             PA12
#define MX_PA12_GPIOx                           GPIOA
#define MX_PA12_PinState                        GPIO_PIN_RESET
#define MX_PA12_GPIO_PuPd                       GPIO_NOPULL
#define MX_PA12_GPIO_Pin                        GPIO_PIN_12
#define MX_PA12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

